### ISSUE TITLE
How to visualize the environment？

### ISSUE THREAD

**Issue by chenci107** [younggyoseo/CaDM#2]
When I run the code, I don't see the visualization related settings. How do I perform the visualization? thanks～

**Comment by younggyoseo** [comment]
For visualization, you can utilize mujoco-py's default render option, but not sure default rendering method supports rendering the robots with different dynamics (e.g., lengths, ..) because we did not modify the xml parts related to geometry, so you should modify that part by yourself if you want the functionality.

Please let me know when you have more questions. Closing the issue for now.

Thanks!
Younggyo
