### ISSUE TITLE
Conflict between version of mujoco-py and baselines

### ISSUE THREAD

**Issue by SigmaTsing** [younggyoseo/CaDM#4]
Hello there, I'm trying to establish an environment for your repo, and I found the version of `baselines` and `mujoco-py` in your readme produce a conflict

The `baselines==0.1.5` package requires `mujoco-py<2.0,>=1.50`, as said in pip, while your repo is using `mujoco-py==2.0.2.9`

Is there any mis-writting in readme, or should I change my installation version ? I'm using python 3.6 with pip version 21.3.1

**Comment by younggyoseo** [comment]
Sorry, I found this Issue late. Are you able to solve the issue? I don't have a virtual environment I used in my machine, so it would be very helpful for me if you could let me know which version of baseline works for you, so that I can update the repo.
If not, I'll investigate more on this.

Thanks!

**Comment by SigmaTsing** [comment]
Nevermind. I've downgraded my mujoco-py and it works for me. The exact version of my mujoco-py is 1.50.1.68 (with baselines == 0.1.5)
